
[general]
	#How much energy for the Electric Furnace to consume to smelt an item per tick
	#Range: > 0
	electricFurnaceEnergySmeltCostPerTick = 100
	#How much energy for the Heat Collector to try and transfer in each direction per tick
	#Range: > 0
	heatCollectorTransferAmountPerTick = 100
	#An example boolean in the server config
	serverBoolean = true
	#An example list of Strings in the server config
	serverStringList = []
	#An example enum DyeColor in the server config
	#Allowed Values: WHITE, ORANGE, MAGENTA, LIGHT_BLUE, YELLOW, LIME, PINK, GRAY, LIGHT_GRAY, CYAN, PURPLE, BLUE, BROWN, GREEN, RED, BLACK
	serverEnumDyeColor = "WHITE"

